AWSTemplateFormatVersion: '2010-09-09'
Description: 'Nested template for databases'

Parameters:
  ServiceName:
    Type: String
    Description: 'Name of the service'

Resources:
  CharactersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${ServiceName}-Characters"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: characterId
          AttributeType: S
      KeySchema:
        - AttributeName: characterId
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  ObjectsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${ServiceName}-Objects"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: objectId
          AttributeType: S
      KeySchema:
        - AttributeName: objectId
          KeyType: HASH

  ActionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${ServiceName}-Actions"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: actionId
          AttributeType: S
      KeySchema:
        - AttributeName: actionId
          KeyType: HASH

  EncountersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${ServiceName}-Encounters"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: encounterId
          AttributeType: S
      KeySchema:
        - AttributeName: encounterId
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  SkillsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${ServiceName}-Skills" # Follow naming convention
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: skillId # Assuming skillId is the primary key
          AttributeType: S
      KeySchema:
        - AttributeName: skillId
          KeyType: HASH

  AttributesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${ServiceName}-Attributes" # Follow naming convention
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: attributeId # Assuming attributeId is the primary key
          AttributeType: S
      KeySchema:
        - AttributeName: attributeId
          KeyType: HASH

  FormulasTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${ServiceName}-Formulas" # Follow naming convention
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: formulaId # Assuming formulaId is the primary key
          AttributeType: S
      KeySchema:
        - AttributeName: formulaId
          KeyType: HASH

  ValuesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${ServiceName}-Values" # Follow naming convention
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: valueId # Assuming valueId is the primary key
          AttributeType: S
      KeySchema:
        - AttributeName: valueId
          KeyType: HASH

Outputs:
  CharactersTableName:
    Description: 'Name of the Characters table'
    Value: !Ref CharactersTable
  ObjectsTableName:
    Description: 'Name of the Objects table'
    Value: !Ref ObjectsTable
  ActionsTableName:
    Description: 'Name of the Actions table'
    Value: !Ref ActionsTable
  EncountersTableName:
    Description: 'Name of the Encounters table'
    Value: !Ref EncountersTable
  SkillsTableName:
    Description: 'Name of the Skills table'
    Value: !Ref SkillsTable
  AttributesTableName:
    Description: 'Name of the Attributes table'
    Value: !Ref AttributesTable
  FormulasTableName:
    Description: 'Name of the Formulas table'
    Value: !Ref FormulasTable
  ValuesTableName:
    Description: 'Name of the Values table'
    Value: !Ref ValuesTable
