# template.yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS AppSync GraphQL API

Parameters:
  Environment:
    Type: String
    Description: 'Deployment environment (prod/qa)'
    Default: 'prod'
    AllowedValues:
      - 'prod'
      - 'qa'
  ServiceName:
    Type: String
    Description: 'Name of the service'
    Default: 'webfg-gql'
  DomainName:
    Type: String
    Description: 'Domain name of the service'
    Default: 'phnks.com'
  PhnksCertArn:
    Type: String
    Description: 'ACM Certificate ARN for phnks.com'
    Default: 'arn:aws:acm:us-east-1:519721258290:certificate/a9b31c8c-0d9a-465d-b677-8fe6a5cceb96'
  PhnksHostedZoneId:
    Type: String
    Description: 'Route53 hosted zone ID for phnks.com'
    Default: 'Z0011216DMAXI27AITHT'
  AppSyncApiName:
    Type: String
    Description: 'Name for the AppSync API'
    Default: 'WEBFG-GQL'
  CharactersDataSourceName:
    Type: String
    Description: 'Name of db data source'
    Default: 'CharactersDataSource'
  ObjectsDataSourceName:
    Type: String
    Description: 'Name of db data source'
    Default: 'ObjectsDataSource'
  ActionsDataSourceName:
    Type: String
    Description: 'Name of db data source'
    Default: 'ActionsDataSource'
  EncountersDataSourceName:
    Type: String
    Description: 'Name of db data source'
    Default: 'EncountersDataSource'
  SkillsDataSourceName: # Add new parameter
    Type: String
    Description: 'Name of Skills db data source'
    Default: 'SkillsDataSource'
  AttributesDataSourceName: # Add new parameter
    Type: String
    Description: 'Name of Attributes db data source'
    Default: 'AttributesDataSource'
  FormulasDataSourceName: # Add new parameter
    Type: String
    Description: 'Name of Formulas db data source'
    Default: 'FormulasDataSource'
  CharactersTableName:
    Type: String
    Description: 'Name of table'
    Default: ''
  ObjectsTableName:
    Type: String
    Description: 'Name of table'
    Default: ''
  ActionsTableName:
    Type: String
    Description: 'Name of table'
    Default: ''
  FormulasTableName: # Add new parameter
    Type: String
    Description: 'Name of Formulas table'
    Default: ''
  EncountersTableName:
    Type: String
    Description: 'Name of table'
    Default: ''
  ValuesTableName: # Add parameter
    Type: String
    Description: 'Name of Values table'
    Default: '' # Added default value
  DeploymentId: # New parameter for PR ID
    Type: String
    Description: 'Unique ID for QA deployments (e.g., PR number)'
    Default: 'none'
  SchemaS3Key:
    Type: String
    Description: S3 key for the GraphQL schema file
  SchemaS3BucketName: # Add parameter to receive bucket name
    Type: String
    Description: Name of the S3 bucket for GraphQL schemas

Conditions:
  IsQA: !Equals [!Ref Environment, 'qa']
  IsQADeployment: !And # New condition for PR-specific QA
    - Condition: IsQA
    - !Not [!Equals [!Ref DeploymentId, 'none']]

Resources:
  DatabasesNestedStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./databases.yaml
      Parameters:
        # Construct ServiceName based on Environment and DeploymentId
        ServiceName: !Sub
          - "${BaseServiceName}${EnvSuffix}${IdSuffix}"
          - BaseServiceName: !Ref ServiceName
            EnvSuffix: !If [ IsQA, "-qa", "" ]
            IdSuffix: !If [ IsQADeployment, !Ref DeploymentId, "" ]

  GraphQLNestedStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./graphql/main.yaml
      Parameters:
        Environment: !Ref Environment
        # Construct AppSyncApiName based on Environment and DeploymentId
        AppSyncApiName: !Sub
          - "${BaseApiName}${EnvSuffix}${IdSuffix}"
          - BaseApiName: !Ref AppSyncApiName
            EnvSuffix: !If [ IsQA, "-qa", "" ]
            IdSuffix: !If [ IsQADeployment, !Ref DeploymentId, "" ]
        # Construct ServiceName based on Environment and DeploymentId
        ServiceName: !Sub
          - "${BaseServiceName}${EnvSuffix}${IdSuffix}"
          - BaseServiceName: !Ref ServiceName
            EnvSuffix: !If [ IsQA, "-qa", "" ]
            IdSuffix: !If [ IsQADeployment, !Ref DeploymentId, "" ]
        CharactersTableName: !GetAtt DatabasesNestedStack.Outputs.CharactersTableName
        ObjectsTableName: !GetAtt DatabasesNestedStack.Outputs.ObjectsTableName
        ActionsTableName: !GetAtt DatabasesNestedStack.Outputs.ActionsTableName
        EncountersTableName: !GetAtt DatabasesNestedStack.Outputs.EncountersTableName
        SkillsTableName: !GetAtt DatabasesNestedStack.Outputs.SkillsTableName # Pass output
        AttributesTableName: !GetAtt DatabasesNestedStack.Outputs.AttributesTableName # Pass output
        CharactersDataSourceName: !Ref CharactersDataSourceName
        ObjectsDataSourceName: !Ref ObjectsDataSourceName
        ActionsDataSourceName: !Ref ActionsDataSourceName
        EncountersDataSourceName: !Ref EncountersDataSourceName
        SkillsDataSourceName: !Ref SkillsDataSourceName # Pass down
        AttributesDataSourceName: !Ref AttributesDataSourceName # Pass down
        FormulasDataSourceName: !Ref FormulasDataSourceName # Pass down
        FormulasTableName: !GetAtt DatabasesNestedStack.Outputs.FormulasTableName # Pass output
        ValuesTableName: !GetAtt DatabasesNestedStack.Outputs.ValuesTableName # Pass output
        PhnksCertArn: !Ref PhnksCertArn
        PhnksHostedZoneId: !Ref PhnksHostedZoneId
        DomainName: !Ref DomainName
        SchemaS3Key: !Ref SchemaS3Key
        SchemaS3BucketName: !Ref SchemaS3BucketName # Pass this parameter down

Outputs:
  GraphQLApiEndpoint:
    Description: 'GraphQL API Endpoint'
    Value: !GetAtt GraphQLNestedStack.Outputs.AppSyncAPIEndpoint
  GraphQLApiKey:
    Description: 'GraphQL API Key'
    Value: !GetAtt GraphQLNestedStack.Outputs.AppSyncAPIKey
