AWSTemplateFormatVersion: '2010-09-09'
Description: 'AppSync Data Sources configuration'

Parameters:
  ApiId:
    Type: String
    Description: 'AppSync GraphQL API ID'
  CharactersDataSourceName:
    Type: String
    Description: 'Name of db data source'
  ObjectsDataSourceName:
    Type: String
    Description: 'Name of db data source'
  ActionsDataSourceName:
    Type: String
    Description: 'Name of db data source'
  EncountersDataSourceName:
    Type: String
    Description: 'Name of db data source'
  CharactersTableName:
    Type: String
    Description: 'Name of table'
  ObjectsTableName:
    Type: String
    Description: 'Name of table'
  ActionsTableName:
    Type: String
    Description: 'Name of table'
  EncountersTableName:
    Type: String
    Description: 'Name of table'
  SkillsTableName: # Add new parameter
    Type: String
    Description: 'Name of Skills table'
  AttributesTableName: # Add new parameter
    Type: String
    Description: 'Name of Attributes table'
  SkillsDataSourceName: # Add new parameter
    Type: String
    Description: 'Name for Skills DynamoDB data source'
  AttributesDataSourceName: # Add new parameter
    Type: String
    Description: 'Name for Attributes DynamoDB data source'
  FormulasDataSourceName: # Add new parameter
    Type: String
    Description: 'Name for Formulas DynamoDB data source'
  FormulasTableName: # Add new parameter
    Type: String
    Description: 'Name of Formulas table'
  # Add parameters for Lambda Function ARNs (passed from template.yaml)
  GetObjectFunctionArn:
    Type: String
    Description: 'ARN of the GetObject Lambda Function'
  ListObjectsFunctionArn:
    Type: String
    Description: 'ARN of the ListObjects Lambda Function'
  CreateObjectFunctionArn:
    Type: String
    Description: 'ARN of the CreateObject Lambda Function'
  UpdateObjectFunctionArn:
    Type: String
    Description: 'ARN of the UpdateObject Lambda Function'
  DeleteObjectFunctionArn:
    Type: String
    Description: 'ARN of the DeleteObject Lambda Function'


Resources:
  AppSyncDynamoDBRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: appsync.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AppSyncDynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:BatchGetItem
                Resource:
                  - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${CharactersTableName}
                  - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${ObjectsTableName}
                  - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${ActionsTableName}
                  - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${EncountersTableName}
                  - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${SkillsTableName} # Add Skills table ARN
                  - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${AttributesTableName} # Add Attributes table ARN
                  - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${FormulasTableName} # Add Formulas table ARN

  AppSyncLambdaServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: appsync.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSAppSyncPushToCloudWatchLogs
      Policies:
        - PolicyName: InvokeLambdaFunction
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: "*"

  CharactersDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !Ref ApiId
      Name: !Ref CharactersDataSourceName
      Type: AMAZON_DYNAMODB
      ServiceRoleArn: !GetAtt AppSyncDynamoDBRole.Arn
      DynamoDBConfig:
        TableName: !Ref CharactersTableName
        AwsRegion: !Sub ${AWS::Region}

  ObjectsDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !Ref ApiId
      Name: !Ref ObjectsDataSourceName
      Type: AMAZON_DYNAMODB
      ServiceRoleArn: !GetAtt AppSyncDynamoDBRole.Arn
      DynamoDBConfig:
        TableName: !Ref ObjectsTableName
        AwsRegion: !Sub ${AWS::Region}

  ActionsDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !Ref ApiId
      Name: !Ref ActionsDataSourceName
      Type: AMAZON_DYNAMODB
      ServiceRoleArn: !GetAtt AppSyncDynamoDBRole.Arn
      DynamoDBConfig:
        TableName: !Ref ActionsTableName
        AwsRegion: !Sub ${AWS::Region}

  EncountersDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !Ref ApiId
      Name: !Ref EncountersDataSourceName
      Type: AMAZON_DYNAMODB
      ServiceRoleArn: !GetAtt AppSyncDynamoDBRole.Arn
      DynamoDBConfig:
        TableName: !Ref EncountersTableName
        AwsRegion: !Sub ${AWS::Region}

  SkillsDataSource: # Add Skills data source
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !Ref ApiId
      Name: !Ref SkillsDataSourceName
      Type: AMAZON_DYNAMODB
      ServiceRoleArn: !GetAtt AppSyncDynamoDBRole.Arn
      DynamoDBConfig:
        TableName: !Ref SkillsTableName
        AwsRegion: !Sub ${AWS::Region}

  AttributesDataSource: # Add Attributes data source
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !Ref ApiId
      Name: !Ref AttributesDataSourceName
      Type: AMAZON_DYNAMODB
      ServiceRoleArn: !GetAtt AppSyncDynamoDBRole.Arn
      DynamoDBConfig:
        TableName: !Ref AttributesTableName
        AwsRegion: !Sub ${AWS::Region}

  FormulasDataSource: # Add Formulas data source
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !Ref ApiId
      Name: !Ref FormulasDataSourceName
      Type: AMAZON_DYNAMODB
      ServiceRoleArn: !GetAtt AppSyncDynamoDBRole.Arn
      DynamoDBConfig:
        TableName: !Ref FormulasTableName
        AwsRegion: !Sub ${AWS::Region}

  # Lambda Data Sources for Object Resolvers
  GetObjectLambdaDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !Ref ApiId
      Name: GetObjectLambdaDataSource # Consistent naming
      Type: AWS_LAMBDA
      ServiceRoleArn: !GetAtt AppSyncLambdaServiceRole.Arn
      LambdaConfig:
        LambdaFunctionArn: !Ref GetObjectFunctionArn

  ListObjectsLambdaDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !Ref ApiId
      Name: ListObjectsLambdaDataSource # Consistent naming
      Type: AWS_LAMBDA
      ServiceRoleArn: !GetAtt AppSyncLambdaServiceRole.Arn
      LambdaConfig:
        LambdaFunctionArn: !Ref ListObjectsFunctionArn

  CreateObjectLambdaDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !Ref ApiId
      Name: CreateObjectLambdaDataSource # Consistent naming
      Type: AWS_LAMBDA
      ServiceRoleArn: !GetAtt AppSyncLambdaServiceRole.Arn
      LambdaConfig:
        LambdaFunctionArn: !Ref CreateObjectFunctionArn

  UpdateObjectLambdaDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !Ref ApiId
      Name: UpdateObjectLambdaDataSource # Consistent naming
      Type: AWS_LAMBDA
      ServiceRoleArn: !GetAtt AppSyncLambdaServiceRole.Arn
      LambdaConfig:
        LambdaFunctionArn: !Ref UpdateObjectFunctionArn

  DeleteObjectLambdaDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !Ref ApiId
      Name: DeleteObjectLambdaDataSource # Consistent naming
      Type: AWS_LAMBDA
      ServiceRoleArn: !GetAtt AppSyncLambdaServiceRole.Arn
      LambdaConfig:
        LambdaFunctionArn: !Ref DeleteObjectFunctionArn

Outputs:
  AppSyncDynamoDBRoleArn:
    Description: 'ARN of the IAM role for AppSync to access DynamoDB'
    Value: !GetAtt AppSyncDynamoDBRole.Arn
  AppSyncLambdaServiceRoleArn:
    Description: 'ARN of the IAM role for AppSync to invoke Lambda functions'
    Value: !GetAtt AppSyncLambdaServiceRole.Arn
  # Add outputs for Lambda Data Source Names
  GetObjectLambdaDataSourceName:
    Description: 'Name of the GetObject Lambda Data Source'
    Value: !Ref GetObjectLambdaDataSource
  ListObjectsLambdaDataSourceName:
    Description: 'Name of the ListObjects Lambda Data Source'
    Value: !Ref ListObjectsLambdaDataSource
  CreateObjectLambdaDataSourceName:
    Description: 'Name of the CreateObject Lambda Data Source'
    Value: !Ref CreateObjectLambdaDataSource
  UpdateObjectLambdaDataSourceName:
    Description: 'Name of the UpdateObject Lambda Data Source'
    Value: !Ref UpdateObjectLambdaDataSource
  DeleteObjectLambdaDataSourceName:
    Description: 'Name of the DeleteObject Lambda Data Source'
    Value: !Ref DeleteObjectLambdaDataSource
