AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'AppSync Encounter Character Resolvers'

Parameters:
  ApiId:
    Type: String
    Description: 'AppSync GraphQL API ID'
  EncountersTableName:
    Type: String
    Description: 'Name of encounters table'
  CharactersTableName:
    Type: String
    Description: 'Name of characters table'
  ActionsTableName:
    Type: String
    Description: 'Name of actions table'
  AppSyncLambdaServiceRoleArn:
    Type: String
    Description: 'Shared lambda service role'

Resources:
  AddCharacterToEncounterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../
      Handler: ./functions/addCharacterToEncounter.handler
      Runtime: nodejs22.x
      MemorySize: 1024
      Timeout: 30
      Environment:
        Variables:
          ENCOUNTERS_TABLE: !Ref EncountersTableName
          CHARACTERS_TABLE: !Ref CharactersTableName
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref EncountersTableName
        - DynamoDBWritePolicy:
            TableName: !Ref EncountersTableName
        - DynamoDBReadPolicy:
            TableName: !Ref CharactersTableName

  RemoveCharacterFromEncounterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../
      Handler: ./functions/removeCharacterFromEncounter.handler
      Runtime: nodejs22.x
      MemorySize: 1024
      Timeout: 30
      Environment:
        Variables:
          ENCOUNTERS_TABLE: !Ref EncountersTableName
          CHARACTERS_TABLE: !Ref CharactersTableName
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref EncountersTableName
        - DynamoDBWritePolicy:
            TableName: !Ref EncountersTableName
        - DynamoDBReadPolicy:
            TableName: !Ref CharactersTableName
            
  # Data sources for Lambda functions
  AddCharacterToEncounterDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !Ref ApiId
      Name: AddCharacterToEncounter
      Type: AWS_LAMBDA
      ServiceRoleArn: !Ref AppSyncLambdaServiceRoleArn
      LambdaConfig:
        LambdaFunctionArn: !GetAtt AddCharacterToEncounterFunction.Arn
  
  RemoveCharacterFromEncounterDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !Ref ApiId
      Name: RemoveCharacterFromEncounter
      Type: AWS_LAMBDA
      ServiceRoleArn: !Ref AppSyncLambdaServiceRoleArn
      LambdaConfig:
        LambdaFunctionArn: !GetAtt RemoveCharacterFromEncounterFunction.Arn