AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Main GraphQL API template'

Parameters:
  Environment:
    Type: String
    Description: 'Deployment environment (prod/qa)'
    AllowedValues:
      - 'prod'
      - 'qa'
  ServiceName:
    Type: String
    Description: 'Name of the service'
  AppSyncApiName:
    Type: String
    Description: 'Name for the AppSync API'
  CharactersDataSourceName:
    Type: String
    Description: 'Name of db data source'
  ObjectsDataSourceName:
    Type: String
    Description: 'Name of db data source'
  ActionsDataSourceName:
    Type: String
    Description: 'Name of db data source'
  EncountersDataSourceName:
    Type: String
    Description: 'Name of db data source'
  CharactersTableName:
    Type: String
    Description: 'Name of table'
  ObjectsTableName:
    Type: String
    Description: 'Name of table'
  ActionsTableName:
    Type: String
    Description: 'Name of table'
  PhnksCertArn:
    Type: String
    Description: 'ARN of the certificate for the custom domain'
  PhnksHostedZoneId:
    Type: String
    Description: 'Hosted Zone ID for the custom domain'
  DomainName:
    Type: String
    Description: 'Domain name of the service'
  SchemaS3Key:
    Type: String
    Description: S3 key for the GraphQL schema file
  SchemaS3BucketName:
    Type: String
    Description: "Name of the S3 bucket containing the GraphQL schema"
  EncountersTableName:
    Type: String
    Description: 'Name of encounters table'

Resources:
  ApiStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./api.yaml 
      Parameters:
        Environment: !Ref Environment
        ServiceName: !Ref ServiceName
        AppSyncApiName: !Ref AppSyncApiName
        PhnksCertArn: !Ref PhnksCertArn
        PhnksHostedZoneId: !Ref PhnksHostedZoneId
        DomainName: !Ref DomainName
        SchemaS3Key: !Ref SchemaS3Key
        SchemaS3BucketName: !Ref SchemaS3BucketName

  DataSourcesStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./data-sources.yaml
      Parameters:
        ApiId: !GetAtt ApiStack.Outputs.GraphQLApiId
        CharactersDataSourceName: !Ref CharactersDataSourceName
        ObjectsDataSourceName: !Ref ObjectsDataSourceName
        ActionsDataSourceName: !Ref ActionsDataSourceName
        EncountersDataSourceName: !Ref EncountersDataSourceName
        CharactersTableName: !Ref CharactersTableName
        ObjectsTableName: !Ref ObjectsTableName
        ActionsTableName: !Ref ActionsTableName
        EncountersTableName: !Ref EncountersTableName

  CharacterResolversStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: DataSourcesStack
    Properties:
      TemplateURL: ./character-resolvers.yaml
      Parameters:
        ApiId: !GetAtt ApiStack.Outputs.GraphQLApiId
        CharactersDataSourceName: !Ref CharactersDataSourceName

  ObjectResolversStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: DataSourcesStack
    Properties:
      TemplateURL: ./object-resolvers.yaml
      Parameters:
        ApiId: !GetAtt ApiStack.Outputs.GraphQLApiId
        ObjectsDataSourceName: !Ref ObjectsDataSourceName

  ActionResolversStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: 
      - DataSourcesStack
      - AppSyncLambdaServiceRole
    Properties:
      TemplateURL: ./action-resolvers.yaml
      Parameters:
        ApiId: !GetAtt ApiStack.Outputs.GraphQLApiId
        ActionsDataSourceName: !Ref ActionsDataSourceName
        ActionsTableName: !Ref ActionsTableName
        AppSyncLambdaServiceRoleArn: !GetAtt AppSyncLambdaServiceRole.Arn
  
  AppSyncLambdaServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: appsync.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSAppSyncPushToCloudWatchLogs
      Policies:
        - PolicyName: InvokeLambdaFunction
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: lambda:InvokeFunction
                Resource: '*'  

  ActionCharacterResolversStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: 
      - DataSourcesStack
      - ApiStack
      - AppSyncLambdaServiceRole
    Properties:
      TemplateURL: ./action-character-resolvers.yaml
      Parameters:
        ApiId: !GetAtt ApiStack.Outputs.GraphQLApiId
        CharactersTableName: !Ref CharactersTableName
        ActionsTableName: !Ref ActionsTableName
        AppSyncLambdaServiceRoleArn: !GetAtt AppSyncLambdaServiceRole.Arn

  ObjectCharacterResolversStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - DataSourcesStack
      - ApiStack
      - AppSyncLambdaServiceRole
    Properties:
      TemplateURL: ./object-character-resolvers.yaml
      Parameters:
        ApiId: !GetAtt ApiStack.Outputs.GraphQLApiId
        CharactersTableName: !Ref CharactersTableName
        ObjectsTableName: !Ref ObjectsTableName
        AppSyncLambdaServiceRoleArn: !GetAtt AppSyncLambdaServiceRole.Arn

  EncounterResolversStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: DataSourcesStack
    Properties:
      TemplateURL: ./encounter-resolvers.yaml
      Parameters:
        ApiId: !GetAtt ApiStack.Outputs.GraphQLApiId
        EncountersDataSourceName: !Ref EncountersDataSourceName

  EncounterCharacterResolversStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - DataSourcesStack
      - ApiStack
      - AppSyncLambdaServiceRole
    Properties:
      TemplateURL: ./encounter-character-resolvers.yaml
      Parameters:
        ApiId: !GetAtt ApiStack.Outputs.GraphQLApiId
        EncountersTableName: !Ref EncountersTableName
        CharactersTableName: !Ref CharactersTableName
        ActionsTableName: !Ref ActionsTableName
        AppSyncLambdaServiceRoleArn: !GetAtt AppSyncLambdaServiceRole.Arn

Outputs:
  AppSyncAPIEndpoint:
    Description: 'GraphQL API Custom Domain'
    Value: !GetAtt ApiStack.Outputs.AppSyncEndpoint
  AppSyncAPIKey:
    Description: 'GraphQL API Key'
    Value: !GetAtt ApiStack.Outputs.AppSyncApiKey