AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'AppSync Object Character Resolvers' # Updated Description

Parameters:
  ApiId:
    Type: String
    Description: 'AppSync GraphQL API ID'
  CharactersTableName:
    Type: String
    Description: 'Name of characters table'
  ObjectsTableName:
    Type: String
    Description: 'Name of objects table'
  AppSyncLambdaServiceRoleArn:
    Type: String
    Description: 'Shared lambda service role'

Resources:
  AddObjectToInventoryFunction: # Keep for now
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../
      Handler: ./functions/addObjectToInventory.handler
      Runtime: nodejs22.x
      MemorySize: 1024
      Timeout: 30
      Environment:
        Variables:
          CHARACTERS_TABLE: !Ref CharactersTableName
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref CharactersTableName
        - DynamoDBWritePolicy:
            TableName: !Ref CharactersTableName

  ResolveCharacterBodyFunction: # Renamed from GetCharacterInventoryFunction
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../
      Handler: ./functions/resolveCharacterBody.handler # Updated handler
      Runtime: nodejs22.x # Keep runtime consistent
      MemorySize: 1024
      Timeout: 30
      Environment:
        Variables:
          OBJECTS_TABLE: !Ref ObjectsTableName
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ObjectsTableName

  AddObjectToInventoryDataSource: # Keep for now
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !Ref ApiId
      Name: AddObjectToInventory
      Type: AWS_LAMBDA
      ServiceRoleArn: !Ref AppSyncLambdaServiceRoleArn
      LambdaConfig:
        LambdaFunctionArn: !GetAtt AddObjectToInventoryFunction.Arn

  ResolveCharacterBodyDataSource: # Renamed from GetCharacterInventoryDataSource
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !Ref ApiId
      Name: ResolveCharacterBody # Updated Name
      Type: AWS_LAMBDA
      ServiceRoleArn: !Ref AppSyncLambdaServiceRoleArn
      LambdaConfig:
        LambdaFunctionArn: !GetAtt ResolveCharacterBodyFunction.Arn # Updated reference

  AddObjectToInventoryResolver: # Keep for now
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !Ref ApiId
      TypeName: Mutation
      FieldName: addObjectToInventory
      DataSourceName: !GetAtt AddObjectToInventoryDataSource.Name
      RequestMappingTemplate: |
        {
          "version": "2018-05-29",
          "operation": "Invoke",
          "payload": {
            "arguments": $util.toJson($ctx.args)
          }
        }
      ResponseMappingTemplate: |
        $util.toJson($ctx.result)

  CharacterBodyResolver: # Renamed from GetCharacterInventoryResolver
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !Ref ApiId
      TypeName: 'Character'
      FieldName: 'body' # Updated field name
      DataSourceName: !GetAtt ResolveCharacterBodyDataSource.Name # Updated data source
      RequestMappingTemplate: |
        {
          "version": "2018-05-29",
          "operation": "Invoke",
          "payload": {
            "source": $util.toJson($context.source)
          }
        }
      ResponseMappingTemplate: |
        $util.toJson($context.result)
