AWSTemplateFormatVersion: '2010-09-09'

Description: 'AppSync Object Resolvers'

Parameters:
  ApiId:
    Type: String
    Description: 'AppSync GraphQL API ID'
  # Update DataSourceName parameters to point to Lambda Data Source Names
  GetObjectLambdaDataSourceName:
    Type: String
    Description: 'Name of the GetObject Lambda data source'
  ListObjectsLambdaDataSourceName:
    Type: String
    Description: 'Name of the ListObjects Lambda data source'
  CreateObjectLambdaDataSourceName:
    Type: String
    Description: 'Name of the CreateObject Lambda data source'
  UpdateObjectLambdaDataSourceName:
    Type: String
    Description: 'Name of the UpdateObject Lambda data source'
  DeleteObjectLambdaDataSourceName:
    Type: String
    Description: 'Name of the DeleteObject Lambda data source'


Resources:
  GetObjectResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !Ref ApiId
      TypeName: 'Query'
      FieldName: 'getObject'
      DataSourceName: !Ref GetObjectLambdaDataSourceName # Use Lambda Data Source
      RequestMappingTemplate: |
        $util.toJson($ctx) # Standard Lambda Request Template
      ResponseMappingTemplate: '$util.toJson($context.result)' # Standard Lambda Response Template

  ListObjectsResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !Ref ApiId
      TypeName: 'Query'
      FieldName: 'listObjects'
      DataSourceName: !Ref ListObjectsLambdaDataSourceName # Use Lambda Data Source
      RequestMappingTemplate: |
        $util.toJson($ctx) # Standard Lambda Request Template
      ResponseMappingTemplate: '$util.toJson($context.result)' # Standard Lambda Response Template

  CreateObjectResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !Ref ApiId
      TypeName: Mutation
      FieldName: createObject
      DataSourceName: !Ref CreateObjectLambdaDataSourceName # Use Lambda Data Source
      RequestMappingTemplate: |
        $util.toJson($ctx) # Standard Lambda Request Template
      ResponseMappingTemplate: '$util.toJson($context.result)' # Standard Lambda Response Template

  UpdateObjectResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !Ref ApiId
      TypeName: Mutation
      FieldName: updateObject
      DataSourceName: !Ref UpdateObjectLambdaDataSourceName # Use Lambda Data Source
      RequestMappingTemplate: |
        $util.toJson($ctx) # Standard Lambda Request Template
      ResponseMappingTemplate: '$util.toJson($context.result)' # Standard Lambda Response Template

  DeleteObjectResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !Ref ApiId
      TypeName: Mutation
      FieldName: deleteObject
      DataSourceName: !Ref DeleteObjectLambdaDataSourceName # Use Lambda Data Source
      RequestMappingTemplate: |
        $util.toJson($ctx) # Standard Lambda Request Template
      ResponseMappingTemplate: '$util.toJson($context.result)' # Standard Lambda Response Template
